spring:
  application:
    name: nuxfood-api

aws:
  region: us-east-1
  profile: pessoal
  sns:
    orders-topic-arn: arn:aws:sns:us-east-1:533267406343:orders-topic
  sqs:
    orders-queue-url: https://sqs.us-east-1.amazonaws.com/533267406343/orders-queue
    orders-express-queue-url: https://sqs.us-east-1.amazonaws.com/533267406343/orders-express-queue
    orders-delivery-queue-url: https://sqs.us-east-1.amazonaws.com/533267406343/orders-delivery-queue-url
    orders-payment-queue-url: https://sqs.us-east-1.amazonaws.com/533267406343/orders-payment-queue-url
cloud:
  aws:
    sqs:
      region: us-east-1

nuxfood:
  orders:
    payment:
      # Total terminando nestes centavos simula falha (ex.: 49.99)
      fail-when-total-ends-with: 99

server:
  port: 8080

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha